OnlineShop/Areas/Admin/Controllers/GroupNewsController.cs
using ClassLibrary;
using Models;
using Models.Framework;
using OnlineShop.Areas.Admin.Code;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class GroupNewsController : Controller
    {
        private GroupNewsModel GroupNews = new GroupNewsModel();

        [Authorize]
        public ActionResult Index()
        {
            return View(GroupNews.List());
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.ParentID = GroupNews.List();
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GroupNew collection)
        {
            ViewBag.ParentID = GroupNews.List();
            collection.CreatedBy = collection.ModifiedBy = CommonFunction.GetSession("AccountLogin");
            if (ModelState.IsValid && GroupNews.Create(collection) == 1)
            {
                TempData["SuccesStatus"] = "Create Success!";
                return RedirectToAction("Create");
            }
            TempData["ErrorStatus"] = "Create Fail!";
            return View(collection);
        }

        [Authorize]
        public ActionResult Edit(int ID)
        {
            ViewBag.ParentID = GroupNews.List();
            return View(GroupNews.ViewDetail(ID));
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GroupNew collection, int ID)
        {
            ViewBag.ParentID = GroupNews.List();
            collection.ModifiedBy = CommonFunction.GetSession("AccountLogin");
            if (ModelState.IsValid && GroupNews.Edit(collection, ID) == 1)
            {
                TempData["SuccesStatus"] = "Update Success!";
                return RedirectToAction("Edit");
            }
            TempData["ErrorStatus"] = "Update Fail!";
            return View(collection);
        }

        [Authorize]
        public ActionResult Delete(int ID)
        {
            if (GroupNews.Delete(ID) == 1)
            {
                TempData["SuccessStatus"] = "Delete Success!";
                return RedirectToAction("Index");
            }
            TempData["ErrorStatus"] = "Delete Fail!";
            return View();
        }
    }
}

OnlineShop/Areas/Admin/Views/GroupNews/Create.cshtml
@model Models.Framework.GroupNew

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutCms.cshtml";
}

@section Container
{
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Add group news</h1>
    <div class="card shadow mb-4">
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.ParentID)
                    @Html.DropDownListFor(model => model.ParentID, new SelectList(@ViewBag.ParentID, "GroupNewsID", "Name"), new { @class = "form-control", multiple = "multiple" } )
                    @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name)
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Detail)
                    @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            }
            <br />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

OnlineShop/Areas/Admin/Views/GroupNews/Edit.cshtml
@model Models.Framework.GroupNew

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutCms.cshtml";
}

@section Container
{
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Edit group news</h1>
    <div class="card shadow mb-4">
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @*<div class="form-group">
                    @Html.LabelFor(model => model.ParentID)
                    @Html.DropDownListFor(model => model.ParentID, new SelectList(@ViewBag.ParentID, "GroupNewsID", "Name"), new { @class = "form-control", multiple = "multiple" })
                    @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                </div>*@
                <div class="form-group">
                    <label for="ParentID">ParentID</label>
                    <select class="form-control" data-val="true" data-val-number="The field ParentID must be a number." id="ParentID" multiple="multiple" name="ParentID">
                        @foreach (var item in @ViewBag.ParentID)
                        {
                            if (item.GroupNewsID != Model.GroupNewsID)
                            {
                                var Selected = (Model.ParentID == @item.GroupNewsID) ? "selected" : "";
                                <option value="@item.GroupNewsID" @Selected>@item.Name</option>
                            }
                        }

                    </select>
                    <span class="field-validation-valid text-danger" data-valmsg-for="ParentID" data-valmsg-replace="true"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name)
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Detail)
                    @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            }
            <br />
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
    }

OnlineShop/Areas/Admin/Views/GroupNews/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutCms.cshtml";
    ViewBag.Title = "Home";
}
@model List<Models.Framework.GroupNew>

@section Container
{

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Group news</h1>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">@Html.ActionLink("Add new", "Create", "GroupNews", null, new { @class = "btn btn-primary" })</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Detail</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Name</th>
                                <th>Detail</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.Detail</td>
                                    <td>
                                        @Html.ActionLink("Delete", "Delete", "GroupNews", new { id = @item.GroupNewsID}, new { onclick="return confirm('Are you sure to delete this item?');" }) | 
                                        @Html.ActionLink("Edit", "Edit", "GroupNews", new { id = @item.GroupNewsID }, null)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
}